complexity:
  TooManyFunctions:
    active: false

style: 
  MaxLineLength:
    excludeCommentStatements: true
  ReturnCount: 
    max: 3
    excludedFunctions:
      # Ignore MenuProvider.onMenuItemSelected, Activity.onOptionsItemSelected,
      # and Fragment.onOptionsItemSelected, because they have a special structure for bug prevention.
      '
        onMenuItemSelected,
        onOptionsItemSelected,
      '
