name: "🧪 Instrumentation Test Matrix"

on:
  workflow_call:

jobs:
  instrumentation:
    name: "${{ matrix.api }}"
    uses: ./.github/workflows/instrumentation.yml
    with:
      android-api: ${{ matrix.api }}
    strategy:
      fail-fast: false
      matrix:
        api:
          #- 15
          #- 21
          - 23
          - 29
          #- 32
          #- 33
