name: "🧪 Instrumentation Test Matrix"

on:
  workflow_call:

jobs:
  instrumentation:
    name: "${{ matrix.api }}"
    uses: ./.github/workflows/instrumentation.yml
    with:
      android-api: ${{ matrix.api }}
      junit5: true
    strategy:
      fail-fast: false
      matrix:
        api:
          #- 15 # Doesn't work with JUnit 5!
          #- 21 # Doesn't work with JUnit 5!
          #- 23 # Doesn't work with JUnit 5!
          - 26
          - 29
          #- 32
          #- 33
