name: "🦺 Validation"

on:
  workflow_call:

jobs:
  gradle-wrapper:
    name: "Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v3

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v1
